# Generated by Django 3.1.5 on 2021-04-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='application_status',
            field=models.IntegerField(choices=[(1, 'PERMANENT'), (2, 'CONTRACT OF SERVICE')], default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='civil_status',
            field=models.IntegerField(choices=[(1, 'SINGLE'), (2, 'MARRIED'), (3, 'WIDOW')], default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE')], default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='station',
            field=models.IntegerField(choices=[(1, 'AFD'), (2, 'RD'), (3, 'RDE'), (4, 'PPSPD')], default=0),
        ),
    ]
