# Generated by Django 3.1.5 on 2021-04-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_no',
            new_name='employee_no',
        ),
    ]
