# Generated by Django 3.1.5 on 2021-04-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210407_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='adjustment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstday_gov',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstday_sra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_adjustment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_promotion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_step_increment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='original_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeligibility',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeligibility',
            name='license_validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeetrainings',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeetrainings',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
