# Generated by Django 3.1.5 on 2021-07-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20210515_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='level',
            field=models.CharField(default='', max_length=20),
        ),
    ]
