# Generated by Django 3.1.5 on 2021-01-19 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210119_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubroute',
            name='user',
        ),
        migrations.AddField(
            model_name='usersubroute',
            name='user_route',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='userSubroute_user_route', to='authentication.userroute'),
            preserve_default=False,
        ),
    ]
