# Generated by Django 3.1.5 on 2021-01-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210119_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubroute',
            name='user_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSubroute_userRoute', to='authentication.userroute'),
        ),
    ]
