# Generated by Django 3.1.5 on 2021-01-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_usersubroute_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroute',
            name='url_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
