# Generated by Django 3.1.5 on 2021-01-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userroute_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroute',
            name='url_name',
        ),
    ]
