# Generated by Django 3.1.5 on 2021-04-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_userroute_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRoute_route', to='authentication.route'),
        ),
        migrations.AlterField(
            model_name='usersubroute',
            name='subroute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSubroute_subroute', to='authentication.subroute'),
        ),
    ]
