# Generated by Django 3.1.5 on 2021-07-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0036_auto_20210701_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollregularmaintenance',
            name='acronym',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
