# Generated by Django 3.1.5 on 2021-07-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0037_payrollregularmaintenance_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductions',
            name='is_gsis',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='payrollregulardatadeductions',
            name='is_gsis',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='payrollregularmaintenance',
            name='deduc_is_gsis',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
