# Generated by Django 3.1.5 on 2021-07-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0038_auto_20210707_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowances',
            name='acount_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='deductions',
            name='acount_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payrollregulardataallowances',
            name='acount_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payrollregulardatadeductions',
            name='acount_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payrollregularmaintenance',
            name='acount_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
